---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-node-affinity
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: namespace-node-affinity
    spec:
      serviceAccountName: namespace-node-affinity
      containers:
      - name: mutator
        image: idgenchev/namespace-node-affinity@sha256:f171d69db71c5fcdb572e19b593e1b3a5b8a4833b482305d51930ee09b0477f9
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-certs
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        env:
          - name: CERT
            value: /etc/webhook/certs/tls.crt
          - name: KEY
            value: /etc/webhook/certs/tls.key
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      initContainers:
      - name: init-webhook
        image: idgenchev/namespace-node-affinity-init-container@sha256:15f1a3c1517169969c037bab72e82cfedd6a042239f867ef8f33a19956a0c361
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-certs
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SERVICE_NAME
            value: namespace-node-affinity
          - name: CERT
            value: /etc/webhook/certs/tls.crt
          - name: KEY
            value: /etc/webhook/certs/tls.key
      volumes:
      - name: webhook-certs
        emptyDir: {}
